meta_product_name: "Run 2 Beat Me"
meta_title: "Run 2 Beat Me - Run faster, win cash"
meta_description: "Challenge your friends and bet money for runs with our mobile app Run2BeatMe"
meta_image: "logo.png" # should exist in `app/assets/images/`
